/**
 * Fabric Gateway Service (per-user signing)
 *
 * Replaces the docker-exec approach in fabricService.js. Each transaction is
 * signed with the identity of the user invoking it — loaded from the DB via
 * fabricCredentialService.
 *
 * Uses fabric-network SDK (already a dependency). Connection profiles are
 * generated by Fablo at fablo-target/fabric-config/connection-profiles/.
 */

const fs = require('fs');
const path = require('path');
const { Gateway, Wallets } = require('fabric-network');
const fabricCredentialService = require('./fabricCredentialService');
const logger = require('../utils/logger');

const CONNECTION_PROFILES_DIR = path.resolve(
  __dirname,
  '../../../fablo-target/fabric-config/connection-profiles'
);

const MSP_TO_PROFILE = {
  UPPSMSP: 'connection-profile-upps.json',
  SekretariatMSP: 'connection-profile-sekretariat.json',
  KEAMSP: 'connection-profile-kea.json',
  AsesorMSP: 'connection-profile-asesor.json',
  MajelisMSP: 'connection-profile-majelis.json',
};

class FabricGatewayService {
  constructor() {
    this._profileCache = {};
  }

  _loadConnectionProfile(mspId) {
    if (this._profileCache[mspId]) return this._profileCache[mspId];
    const file = MSP_TO_PROFILE[mspId];
    if (!file) throw new Error(`No connection profile mapped for MSP: ${mspId}`);
    const fullPath = path.join(CONNECTION_PROFILES_DIR, file);
    if (!fs.existsSync(fullPath)) {
      throw new Error(`Connection profile not found: ${fullPath}`);
    }
    const profile = JSON.parse(fs.readFileSync(fullPath, 'utf8'));
    this._profileCache[mspId] = profile;
    return profile;
  }

  async _buildWalletIdentity(credentials) {
    const wallet = await Wallets.newInMemoryWallet();
    await wallet.put(credentials.userId, {
      credentials: {
        certificate: credentials.certificate,
        privateKey: credentials.privateKey,
      },
      mspId: credentials.mspId,
      type: 'X.509',
    });
    return { wallet, identityLabel: credentials.userId };
  }

  async _withGateway(userId, action) {
    const credentials = await fabricCredentialService.getCredentials(userId);
    const profile = this._loadConnectionProfile(credentials.mspId);
    const { wallet, identityLabel } = await this._buildWalletIdentity(credentials);

    const gateway = new Gateway();
    try {
      await gateway.connect(profile, {
        wallet,
        identity: identityLabel,
        discovery: { enabled: true, asLocalhost: true },
      });
      return await action(gateway);
    } finally {
      gateway.disconnect();
    }
  }

  /**
   * Submit a transaction (write). Signed by the user's identity.
   * @returns {Promise<any>} Parsed JSON response, or raw string if not JSON.
   */
  async submitTransaction(userId, functionName, args = []) {
    logger.info(`[Gateway] submitTransaction userId=${userId} fn=${functionName} args=${args.length}`);
    return await this._withGateway(userId, async (gateway) => {
      const network = await gateway.getNetwork('akreditasi');
      const contract = network.getContract('submission-contract');
      const payload = await contract.submitTransaction(functionName, ...args);
      const resultStr = payload.toString();
      try {
        return JSON.parse(resultStr);
      } catch {
        return resultStr;
      }
    });
  }

  /**
   * Evaluate a transaction (read). Signed by the user's identity.
   */
  async evaluateTransaction(userId, functionName, args = []) {
    logger.info(`[Gateway] evaluateTransaction userId=${userId} fn=${functionName}`);
    return await this._withGateway(userId, async (gateway) => {
      const network = await gateway.getNetwork('akreditasi');
      const contract = network.getContract('submission-contract');
      const payload = await contract.evaluateTransaction(functionName, ...args);
      const resultStr = payload.toString();
      try {
        return JSON.parse(resultStr);
      } catch {
        return resultStr;
      }
    });
  }
}

module.exports = new FabricGatewayService();
